cnn:
  test:
    features_path: data/test/test_features.npy
    labels_path: data/test/test_labels.npy
  train:
    early_stopping: 15
    epochs: 200
    features_path: data/train/train_features.npy
    labels_path: data/train/train_labels.npy
    learning_rate: 0.01
    save_model_at: model_weights/cnn
    train_BS: 64
    val_size: 0.15
    valid_BS: 64
device: cpu
lstm:
  test:
    features_path: data/test/test_features.npy
    labels_path: data/test/test_labels.npy
  train:
    early_stopping: 15
    epochs: 200
    features_path: data/train/train_features.npy
    labels_path: data/train/train_labels.npy
    learning_rate: 0.01
    save_model_at: model_weights/lstm
    train_BS: 64
    val_size: 0.15
    valid_BS: 64
preprocessing:
  audio_dir: raw_data/split_data
  csv_path: raw_data/split_data.csv
  test: data/test/
  train: data/train/
sample_rate: 16000
transformer:
  test:
    features_path: data/test/test_features.npy
    labels_path: data/test/test_labels.npy
  train:
    early_stopping: 15
    epochs: 200
    features_path: data/train/train_features.npy
    labels_path: data/train/train_labels.npy
    learning_rate: 0.01
    model_params:
      dropout: 0.3
      embed_dim: 256
      hidden_dim: 512
      num_classes: 8
      num_heads: 8
      num_layers: 48
      num_patches: 65
    save_model_at: model_weights/transformer
    train_BS: 64
    val_size: 0.15
    valid_BS: 64
