#CNN Transformer config files
device: "cuda"
sample_rate: 16000

cnn:
  train:
    features_path:  "data/train/train_features.npy"
    labels_path: "data/train/train_labels.npy"
    val_size: 0.15
    epochs: 200
    early_stopping: 15
    train_BS: 64
    valid_BS: 64
    learning_rate: 0.01
    save_model_at: "model_weights/cnn"

    early_stopping: 15
    train_BS: 64
    valid_BS: 64
    epochs: 500
     
  test:
    features_path:  "data/test/test_features.npy"
    labels_path: "data/test/test_labels.npy"

transformer:
  train:
    features_path:  "data/train/train_features.npy"
    labels_path: "data/train/train_labels.npy"
    val_size: 0.15
    epochs: 500
    early_stopping: 15
    train_BS: 64
    valid_BS: 64
    learning_rate: 0.01
    save_model_at: "model_weights/transformer"

    early_stopping: 15
    train_BS: 64
    valid_BS: 64
    epochs: 1
    
    model_params: 
      embed_dim: 256
      hidden_dim: 512
      num_heads: 8
      num_layers: 36
      dropout: 0.3
      num_classes: 8
      num_patches: 65  
      
     
  test:
    features_path:  "data/test/test_features.npy"
    labels_path: "data/test/test_labels.npy"

  
lstm:
  train:
    features_path:  "data/train/train_features.npy"
    labels_path: "data/train/train_labels.npy"
    val_size: 0.15
    epochs: 200
    early_stopping: 15
    train_BS: 64
    valid_BS: 64
    learning_rate: 0.01
    save_model_at: "model_weights/lstm"

    early_stopping: 15
    train_BS: 64
    valid_BS: 64
    epochs: 500
     
  test:
    features_path:  "data/test/test_features.npy"
    labels_path: "data/test/test_labels.npy"
